### PR TITLE
Main page

### PR DESCRIPTION
**Pull request by franklinben23**
We worked on the project together from start to finish, everything was set up properly and only lacked minor stylistic modifications due to a time constraint.

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS : CHANGES REQUIRED :red_circle: :recycle: 

Hey team :wave:  :wave: , you guys did well on this project :clap:  . however, lets make a few more changes :arrow_down: 

- [x]  The NY logo should be a link

- [x] There is a horizontal scrollbar on your page, fix that too.

- [x] The editor picks section should float to the left side of the page. Add some margin between the text and the editor's section. check the screenshot below :arrow_down: 

*Original*
ori

*Clone*
cl

- [x] You are missing the following section on your page, kindly add it.
mis


- [x] You are missing the footer section, kindly add it

- [x]  Fix the failing stylelint errors

Thats all :smile: , please submit another review when done.

Regards
Peris Ndanu
Feel free to slack me anytime if you have any questions

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi @franklinben23 and @gscarv13  ! 👋 👋 👋 
### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended**

- [x] The NYT logo is currently broken, it probably is due to a fault in the link. Also, fix the navbar to look as similar as possible to the actual site.

**Original**

Screenshot (31)

**Yours**

Screenshot (38)


- [x] Fix the social media row to look as similar as possible to the actual site's.

**Original**

Screenshot (17)

**Yours**

Screenshot (39)


- [x] Adjust the "Theory of Inflation" section to look as similar as possible to the actual site's.

- [x] Fix the section before the footer.


**Original**

Screenshot (41)


**Yours**

Screenshot (40)

- [x] Please fix your footer to look like the actual site's.

**Original**

Screenshot (23)


**Yours**

Screenshot (42)




__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by franklinben23** [comment]
The link at the top is working well at each one's computer (also working on the Gihub Pages), the problems with it must be native to the user's browser.

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello team :wave: 
Well done on getting the project to this level. 
Just a little more changes to be made.
- [x] You nav still doesn't look like the original. Please refer to the previous reviewer's comment on your nav and make it look like the original.
- [x] The aside editor's pick section still doesn't look like it is in the original. Refer to the previous reviewer's comment on that.
- [ ] Please work on the Most Popular section' and the 'Suggested newsletters for you' section to make it look like it is in the original.

Please make another review when you are done.
slack(@ebeagusamuel)

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello team
Just one final change to make and you will get this project approved.
- [ ] The "More in space and astronomy section" should have 3 elements in a row and not 2. 

Fix this and your project should be approved in the next review
slack(@ebeagusamuel)

**Comment by gscarv13** [comment]
Hello Ebeagu,

This is how the page looks here, there are no problems:
- Screenshot 1:

Capturar1

- Screenshot 2:

captura

**Review by ebeagusamuel — APPROVED** [review]
# Project Approved :champagne: 
Congratulations :clap: :clap: 
You have now met the requirements for this project and can now merge this branch.

I wish you good luck with the next project :+1: 
slack(@ebeagusamuel)

**Pull request merged**
